using AtlusScriptCompiler;
using AtlusScriptLibrary.Common.Logging;
using AtlusScriptLibrary.Common.Text.Encodings;
using MetroSet_UI.Forms;
using Newtonsoft.Json;
using ShrineFox.IO;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Windows.Forms;
using AtlusFileSystemLibrary;
using AtlusFileSystemLibrary.Common.IO;
using AtlusFileSystemLibrary.FileSystems.PAK;
using System.Linq;

namespace AtlusMSGEditor
{
    public partial class MainForm : MetroSetForm
    {
        public Encoding userEncoding = AtlusEncoding.Persona5RoyalEFIGS;
        public string dumpInputPath = "";
        public string dumpOutPath = ".\\Dump";
        public string exportPath = ".\\Output";
        public string defaultJson = ".\\Dependencies\\msgDirs.json";
        public int selectedDir = 0;
        public int selectedFile = 0;
        public int selectedMsg = 0;

        public MainForm()
        {
            InitializeComponent();

            // Setup form appearance
            ApplyTheme();
            SetLogging();
            MenuStripHelper.SetMenuStripIcons(MenuStripHelper.GetMenuStripIconPairs("Icons.txt"), this);

            // Set default encoding to first available value
            comboBox_Encoding.SelectedIndex = 0;
            // Load default JSON dump if it exists
            if (File.Exists(defaultJson))
                MsgDirs = JsonConvert.DeserializeObject<List<MsgDir>>(File.ReadAllText(defaultJson));

            // Apply loaded data to editor controls
            SetDirectoryListBoxDataSource();
        }

        private void SetLogging()
        {
            Output.Logging = true;
            Output.LogPath = "Log.txt";
            Output.LogToFile = true;
            Output.LogControl = rtb_Log;
            Output.VerboseLogging = true;
        }

        // Data loaded from script dump for viewing/editing in form
        public List<MsgDir> MsgDirs = new List<MsgDir>();

        // Data generated by user by editing, used to generate exported files
        public static Settings UserSettings = new Settings();

        public class Settings
        {
            public List<Change> Changes { get; set; } = new List<Change>();
            public List<Replacement> Replacements { get; set; } = new List<Replacement>();
        }

        public class Replacement
        {
            public string TextToReplace { get; set; } = "";
            public string ReplacementText { get; set; } = "";

        }

        public class Change
        {
            public string Path { get; set; } = "";
            public string MsgName { get; set; } = "";
            public string MsgText { get; set; } = "";
            public string Speaker { get; set; } = "";
        }

        public class MsgDir
        {
            public int Id { get; set; } = 0;
            public string Path { get; set; } = "";
            public List<MsgFile> MsgFiles { get; set; } = new List<MsgFile>();
        }

        public class MsgFile
        {
            public int Id { get; set; } = 0;
            public string Path { get; set; } = "";
            public bool UsedByBf { get; set; } = false;
            public List<Message> Messages { get; set; } = new List<Message>();
        }

        public class Message
        {
            public int Id { get; set; } = 0;
            public string Name { get; set; } = "";
            public string Text { get; set; } = "";
            public string Speaker { get; set; } = "";
            public bool IsSelection { get; set; } = false;
            public Change Change { get; set; } = null;
        }
    }
}